# Generated by Django 5.1.6 on 2025-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorsession',
            name='start_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
