# Generated by Django 5.1.6 on 2025-03-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_motorsession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='geburtsdatum',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorsession',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
